version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
